export const data = [
    {
        id: 1,
        "Image": "https://touchcinema.com/uploads/phim-2021/1200wx1800h-7-poster.jpg",

        "Title": "Batman: Vạch Trần Sự Thật",
        "des": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 2,
        "Image": "https://rapchieuphim.com/photos/8925/279482629_1902242109978305_595463878467319827_n.jpg",
        "Title": " Avatar: Dòng Chảy Của Nước",
        "des": "Jake Sully lives with his newfound family formed on the planet of Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their planet.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 3,
        "Image": "https://cinematone.info/public/poster-22/220908232132_glass_onion_a_knives_out_mystery_59xXT.jpg",
        "Title": "Kẻ Đâm Lén: Glass Onion",
        "des": "Famed Southern detective Benoit Blanc travels to Greece for his latest case.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 4,
        "Image": "https://m.media-amazon.com/images/M/MV5BMWM5YTRlNjYtNGRlMy00M2U5LTgyMTItMmFhODUzNDcxMWVhXkEyXkFqcGdeQXVyMjU5OTg0MTQ@._V1_.jpg",
        "Title": "Argylle",
        "des": "The world's greatest spy, 'Argylle,' gets caught up in a globe-trotting adventure.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 5,
        "Image": "https://fr.web.img3.acsta.net/pictures/22/01/14/11/39/5317694.jpg",
        "Title": "Killers of the Flower Moon",
        "des": "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s sparking a major F.B.I. investigation involving J. Edgar Hoover.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 6,
        "Image": "https://pics.filmaffinity.com/Spider_Man_Across_the_Spider_Verse-524691364-large.jpg",
        "Title": " Spider-Man: Across the Spider-Verse",
        "des": "Miles Morales returns for the next chapter of the Oscar®-winning Spider-Verse saga, an epic adventure that will transport Brooklyn's full-time",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 7,
        "Image": "https://thegioidienanh.vn/stores/news_dataimages/yenlinh/062022/23/12/3401_rva3UhKaMeiB0Vej5A2pm1leX7K.jpg?rt=20220623123411",
        "Title": " Elvis",
        "des": "The life of American music icon Elvis Presley, from his childhood to becoming a rock and movie star in the 1950s while maintaining a complex relationship with his manager, Colonel Tom Parker.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 8,
        "Image": "https://m.media-amazon.com/images/M/MV5BZmM4MWIwMGItYzA3ZC00MDY4LTlhNWQtY2MwOTViODk1M2U1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
        "Title": " Babylon",
        "des": "Set in Hollywood during the transition from silent films to talkies, focusing on a mixture of historical & fictional characters.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 9,
        "Image": "https://m.media-amazon.com/images/M/MV5BMTg0NjEwNjUxM15BMl5BanBnXkFtZTcwMzk0MjQ5Mg@@.jpg%3Cbr%20/%3E",
        "Title": " Sherlock Holmes 3",
        "des": "The plot is unknown at this time.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 10,
        "Image": "https://www.cgv.vn/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/t/u/turning_red-final_poster_1_.jpg",
        "Title": "TURNING RED",
        "des": "Mei Lee is a confident, dorky thirteen-year-old torn between staying her mother's dutiful daughter and the chaos of adolescence. And as if changes to her interests, relationships, and body weren't enough, whenever she gets too excited, she 'poofs' into a giant red panda!",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 11,
        "Image": "https://m.media-amazon.com/images/M/MV5BODgzZGEwZGQtZjA2Mi00OTI5LWIwZmYtZDQ4OTMxODE0YmU4XkEyXkFqcGdeQXVyOTQ5MDIyNDM@._V1_FMjpg_UX1000_.jpg",
        "Title": "Marcel the Shell with Shoes On",
        "des": "Marcel is an adorable one-inch-tall shell who ekes out a colorful existence with his grandmother Connie and their pet lint, Alan. Once part of a sprawling community of shells.",
        "Year": "1977",
        "Nation": "USA",
    },
]